# Generated by Django 4.2.13 on 2024-06-28 17:56

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('thumbnail', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=image_cropping.fields.ImageCropField(upload_to='thumbnails/'),
        ),
    ]
